version: '3.3'

volumes:
  pg_data:
  static:
  data:

services:

  db:
    image: postgres:13
    volumes:
      - pg_data:/var/lib/postgresql/data
    env_file: .env

  redis:
    image: redis:latest
    command: redis-server --port 6380
    container_name: redis
    ports:
      - "6380:6380"
    depends_on:
      - db

  backend:
    build: ./picasso/
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - static:/backend_static/
      - data:/data/
    env_file: .env
    depends_on:
      - redis
      - celery

  celery:
    build: ./picasso/
    command: python -m celery -A picasso worker -l info
    volumes:
      - static:/backend_static/
      - data:/data/
    env_file: .env
    depends_on:
      - redis

  gateway:
    build: ./docker/nginx/
    volumes:
      - static:/staticfiles/
      - data:/data/
    env_file: .env
    ports:
      - 8010:80
    depends_on:
      - backend